Feature/set target framework to netstandard 20
SwedbankPay/swedbank-pay-sdk-dotnet pull request #248
Opened 2021-02-08 07:15 UTC by NullableInt

2021-02-08 08:09 UTC, asbjornu requested changes
If we're building for several different framework versions, we need to introduce `matrix` into the GitHub Actions workflow, no? Also, the tests are failing.

2021-02-08 08:09 UTC, asbjornu commented on src/SwedbankPay.Sdk.Infrastructure/Extensions/EnumExtensions.cs
> +        public static TEnum Parse<TEnum>(String value) where TEnum : struct
Make this into a proper extension method so the word `Extensions` make sense.

```suggestion
    public static class StringExtensions
    {
        public static TEnum ToEnum<TEnum>(this string value) where TEnum : struct
```

2021-02-08 08:17 UTC, NullableInt commented
> 
> 
> If we're building for several different framework versions, we need to introduce `matrix` into the GitHub Actions workflow, no? Also, the tests are failing.

Where do you want matrix testing? And on what?

Test failed due to `{"name":"Transactions[1].Activities","description":"Activity chain is broken."}` meaning we have to re run the test after a few minutes. This is not an error in production and only happens on external integration.

2021-02-08 09:06 UTC, asbjornu requested changes
>Where do you want matrix testing? And on what?

[`matrix`](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix) is used to parameterize every `job` for a different global variable, usually specifying the environment.

We should perform `dotnet build`, `dotnet test`, etc., for each version of .NET we claim to support, no?

2021-02-08 09:06 UTC, asbjornu commented on src/SwedbankPay.Sdk.Infrastructure/PaymentInstruments/Card/CardPayment.cs
> +            Instrument = StringExtensions.Parse<PaymentInstrument>(payment.Instrument);
```suggestion
            Instrument = payment.Instrument.ParseTo<PaymentInstrument>();

```

2021-02-08 09:06 UTC, asbjornu commented on src/SwedbankPay.Sdk.Infrastructure/Extensions/StringExtensions.cs
> +        public static TEnum Parse<TEnum>(this string value) where TEnum : struct
```suggestion
        public static TEnum ParseTo<TEnum>(this string value) where TEnum : struct
```

2021-02-08 09:06 UTC, asbjornu commented on src/SwedbankPay.Sdk.Infrastructure/PaymentInstruments/Card/CardPayment.cs
> +                Intent = StringExtensions.Parse<PaymentIntent>(payment.Intent);
```suggestion
                Intent = payment.Intent.ParseTo<PaymentIntent>();

```

2021-02-08 09:20 UTC, NullableInt commented
> 
> 
> > Where do you want matrix testing? And on what?
> 
> [`matrix`](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix) is used to parameterize every `job` for a different global variable, usually specifying the environment.
> 
> We should perform `dotnet build`, `dotnet test`, etc., for each version of .NET we claim to support, no?

I can set this up for the test step. But each run will take approximately 19 minutes.

2021-02-08 10:30 UTC, NullableInt commented
> 
> 
> > > Where do you want matrix testing? And on what?
> > 
> > 
> > [`matrix`](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix) is used to parameterize every `job` for a different global variable, usually specifying the environment.
> > We should perform `dotnet build`, `dotnet test`, etc., for each version of .NET we claim to support, no?
> 
> I can set this up for the test step. But each run will take approximately 19 minutes for each configuration.

Looking into it this will not work as the test projects does not use the nuget (nor should they), so I'll need to come up with a different way of testing this.

2021-02-08 15:04 UTC, NullableInt commented
@asbjornu Can we do matrix testing in a different pull request?

2021-02-09 12:58 UTC, asbjornu commented
> @asbjornu Can we do matrix testing in a different pull request?

Yes, absolutely.

2021-02-09 12:58 UTC, asbjornu approved these changes

2021-02-09 13:27 UTC, merged